### ISSUE TITLE
讨论项目细节

### ISSUE THREAD

**Issue by vcjmhg** [code-with-no-bug/OperatorManager#1]
在完成直播答疑之后，讨论出一个可行的需求分析方案

**Comment by vcjmhg** [comment]
@Hats-Wang 
我们可以先定一个简单的写作思路，基本功能我们可以参考OLM，它具有的功能的我们暂且都可以写上。因为初赛只是提交一个文档，并且靠文档优劣来评定能否晋级，因而我们尽可能将文档写的高大上一点:smile:.。
具体可以参考OLM的说明文档https://olm.operatorframework.io/docs/tasks/

**Comment by Hats-Wang** [comment]
我觉得现在可以先更新一下简历，文档第四个要提供技术能力证明 @vcjmhg 而且另外一位同学没有进来？

**Comment by vcjmhg** [comment]
> 我觉得现在可以先更新一下简历，文档第四个要提供技术能力证明 @vcjmhg 而且另外一位同学没有进来？

ok，我们可以直接在腾讯文档的设计文档里进行修改。另一位同学我邀请过了哈，可能没看到吧，稍后我在群里说一下哈。

上边那个只是提供一个思路，建议可以提前看一看文档，然后等老师直播结束后，我们再针对题目的具体要求来商量具体内容。

**Comment by vcjmhg** [comment]
@Hats-Wang，简历好像是格式不限，我们应该可以以附件的形式发过去
